# Generated by Django 3.0 on 2024-01-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_brand', models.CharField(choices=[('apple', 'apple'), ('mi', 'mi'), ('fitbit', 'fitbit'), ('samsung', 'samsung')], max_length=100)),
                ('watch_model', models.CharField(max_length=100)),
                ('watch_desc', models.TextField()),
                ('watch_price', models.IntegerField()),
                ('watch_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
