# Generated by Django 3.0 on 2024-01-28 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='watch_seller',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='watch_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
